// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projBCC2.Models;

#nullable disable

namespace projBCC2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221124023943_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("projBCC2.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("estadoCliente")
                        .HasColumnType("int");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("projBCC2.Models.Compra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("empresaid")
                        .HasColumnType("int");

                    b.Property<int>("funcionarioid")
                        .HasColumnType("int");

                    b.Property<string>("produto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("quantidadeCompra")
                        .HasColumnType("int");

                    b.Property<float>("valorUN")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("empresaid");

                    b.HasIndex("funcionarioid");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("projBCC2.Models.Empresa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("estadoEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("nomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("projBCC2.Models.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("funcao")
                        .HasColumnType("int");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nomeCliente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("id");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("projBCC2.Models.Movimentacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("comprasid")
                        .HasColumnType("int");

                    b.Property<int>("comprastotal")
                        .HasColumnType("int");

                    b.Property<int?>("revendaid")
                        .HasColumnType("int");

                    b.Property<int>("revendastotal")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("comprasid");

                    b.HasIndex("revendaid");

                    b.ToTable("Balancete");
                });

            modelBuilder.Entity("projBCC2.Models.Produto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("compraid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("compraid");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("projBCC2.Models.Revenda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("clienteid")
                        .HasColumnType("int");

                    b.Property<int?>("compraid")
                        .HasColumnType("int");

                    b.Property<int?>("comprasid")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<int>("quantidadeVenda")
                        .HasColumnType("int");

                    b.Property<int>("valorUN")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("clienteid");

                    b.HasIndex("compraid");

                    b.HasIndex("comprasid");

                    b.ToTable("Revenda");
                });

            modelBuilder.Entity("projBCC2.Models.Compra", b =>
                {
                    b.HasOne("projBCC2.Models.Empresa", "empresa")
                        .WithMany()
                        .HasForeignKey("empresaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projBCC2.Models.Funcionario", "funcionario")
                        .WithMany()
                        .HasForeignKey("funcionarioid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("empresa");

                    b.Navigation("funcionario");
                });

            modelBuilder.Entity("projBCC2.Models.Movimentacao", b =>
                {
                    b.HasOne("projBCC2.Models.Compra", "compras")
                        .WithMany()
                        .HasForeignKey("comprasid");

                    b.HasOne("projBCC2.Models.Revenda", "revenda")
                        .WithMany()
                        .HasForeignKey("revendaid");

                    b.Navigation("compras");

                    b.Navigation("revenda");
                });

            modelBuilder.Entity("projBCC2.Models.Produto", b =>
                {
                    b.HasOne("projBCC2.Models.Compra", "compra")
                        .WithMany()
                        .HasForeignKey("compraid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compra");
                });

            modelBuilder.Entity("projBCC2.Models.Revenda", b =>
                {
                    b.HasOne("projBCC2.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projBCC2.Models.Compra", "compra")
                        .WithMany()
                        .HasForeignKey("compraid");

                    b.HasOne("projBCC2.Models.Compra", "compras")
                        .WithMany()
                        .HasForeignKey("comprasid");

                    b.Navigation("cliente");

                    b.Navigation("compra");

                    b.Navigation("compras");
                });
#pragma warning restore 612, 618
        }
    }
}
